name: ${project.name}
main: us.higashiyama.george.SQTurrets.SQTurrets
version: ${project.version}
commands:
  turretsreload:
  turretlist:
    description: List all turrets you have permission to use
    usage: /turretlist
   