name: ${project.name}
version: ${project.version}
main: us.higashiyama.george.SQTurrets.SQTurrets
depend: [SQEmpire]

commands:
  turretsreload:
  turretlist:
    description: List all turrets you have permission to use
    usage: /<command>
   