name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
depend: [Movecraft, SQDatabase]
commands:
  apocalypse:
    description: Apocalypse information.
    usage: /<command> score or /apoc top
    aliases: [apoc, sqapocalypse]
