name: ${project.name}
main: com.starquestminecraft.sqapocalypse.SQApocalypse
version: ${project.version}
commands:
  apocalypse:
    description: apocalypse information.
    usage: /apoc score or /apoc top
    aliases: [apoc, sqapocalypse]
depend: [Movecraft]