ranks:
  Requiem1:
    prereq: Requiem0
    price: 10.0
    skill: all
    level: 10
  Requiem2:
    prereq: Requiem1
    price: 15.0
    skill: all
    level: 30
  Requiem3:
    prereq: Requiem2
    price: 20.0
    skill: all
    level: 50