name: ${project.version}
version: ${project.version}
main: com.starquestminecraft.SQRanks4.SQRanks4
depend: [StarQuest]

commands:
  rankup:
     description: Purchase a rank wih credits.
     usage: /rankup
     permission: SQRanks4.buyrank
     permission-message: You don't have permission to use this command.
  ranklist:
    description: Get a list of all ranks and their requirements.
    usage: /ranklist
    permission: SQRanks4.buyrank
    permission-message: You don't have permission to use this command.