name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.starquestminecraft.sqtowerdefence.SQTowerDefence
depend: [StarQuest, SQTechBase]
loadbefore: [SQAutomators]