name: ${project.name}
version: ${project.version}
main: com.dibujaron.powerboostpurchaser.PowerboostPurchaser
depend: [Factions, Movecraft]
commands:
   powerboost:
      description: manage personal or faction power boosts.
      usage: /powerboost <faction/personal> [cancel / (purchase <value>)]
   taxes:
      description: manage your faction's taxes.
      usage: /taxes [set <value>]