name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.starquestminecraft.sqtechbase.SQTechBase
softdepend: [Movecraft]
commands:
   sqtech:
     description: Manages SQTech