ranks:
  refugee:
      credits: 0
      infamyGain: -3
      infamyCost: 0
      next:
        - settler
  settler:
      credits: 10000
      infamyGain: 0
      infamyCost: 0
      next:
        - colonist
        - pirate
  colonist:
      credits: 50000
      infamyGain: 1
      infamyCost: 0
      next:
        - citizen
  citizen:
      credits: 250000
      infamyGain: 2
      infamyCost: 0
      next:
        - affluent
  affluent:
      credits: 1250000
      infamyGain: 4
      infamyCost: 0
      next:
        - tycoon
  tycoon:
      credits: 6250000
      infamyGain: 6
      infamyCost: 0
  pirate:
      credits: 0
      infamyCost: 5
      infamyGain: 2
      next:
        - corsair
  corsair:
      credits: 0
      infamyGain: 3
      infamyCost: 20
      next:
        - buccaneer
  buccaneer:
      credits: 0
      infamyGain: 5
      infamyCost: 80
      next:
        - warlord
  warlord:
      credits: 0
      infamyGain: 7
      infamyCost: 160
multiplier: 1