name: ${project.name}
main: com.regalphoenixmc.SQRankup.SQRankup
version: ${project.version}
softdepend: [PermissionsEx]
depend: [Vault]
commands:
  rankup:
    description: Rank up!
    usage: /rankup
  addapp:
    description: Mark a player as applied.
    usage: /addapp <Player>
  rankuprefresh:
    description: Refresh Rankup Multiplier
  rankupmultiplier:
    description: Set a kill multiplier
    usage: /rankupmultiplier <int>
  resetrank:
    description: Reset a player's rank
    usage: /resetrank <player>

   