name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Lyneira
website: http://dev.bukkit.org/server-mods/machinacraft/
dev-url: http://dev.bukkit.org/server-mods/machinacraft/
main: me.lyneira.MachinaCore.MachinaCore