name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
commands:
    spawnsail:
        description: generate a sail!
        usage: /<command>