name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
commands:
  autorestart:
    description: Stop the server in one second.
    usage: /<command>
  restartall:
    description: Restart the server.
    permission: SQAutoRestart.restartall
    usage: /<command> <time delay>

