name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.ginger_walnut.sqsmoothcraft.SQSmoothCraft
depend: [ProtocolLib, StarQuest]

commands:
  ship:
    description: main command for SQSmoothCraft
  hs:
    description: main command for Heat Seeking Missiles

permissions:
  SQSmoothCraft.spawnShip:
    description: Permission node for spawning a default smoothcraft ship