name: ${project.name}
version: ${project.version}
author: lawrencethefrog
main: com.whirlwindgames.sqorbits.mover.SQOrbitsPlanetMover
softdepend: [dynmap, WorldEdit, WorldGuard]

commands:
  whereis:
    description: Shows the coordinates of a planet (or all planets in system if unspecified)
    usage: /whereis <planet>
    permission: sqorbits.whereis
    permission-message: You don't have permission to view the coordiantes of planets.