ignoreData:
  - DISPENSER
  - PISTON_STICKY_BASE
  - PISTON_BASE
  - CHEST
  - FURNACE
  - SIGN_POST
  - WALL_SIGN
  - WOODEN_DOOR
  - LADDER
  - LEVER
  - REDSTONE_TORCH_ON
  - REDSTONE_TORCH_OFF
  - STONE_BOTTON
  - TRAP_DOOR
  - FENCE_GATE
  - TRAPPED_CHEST
  - HOPPER
  - DROPPER
  - LOG
  - LOG_2
  - HAY_BLOCK
  - BIRCH_FENCE
  - BIRCH_FENCE_GATE
  - BIRCH_DOOR
  - SPRUCE_FENCE
  - SPRUCE_FENCE_GATE
  - SPRUCE_DOOR
  - JUNGLE_FENCE
  - JUNGLE_FENCE_GATE
  - JUNGLE_DOOR
  - DARK_OAK_FENCE
  - DARK_OAK_FENCE_GATE
  - DARK_OAK_DOOR
  - ACACIA_FENCE
  - ACACIA_FENCE_GATE
  - ACACIA_DOOR
  - WOOD_STAIRS
  - COBBLESTONE_STAIRS
  - BRICK_STAIRS
  - SMOOTH_STAIRS
  - NETHER_BRICK_STAIRS
  - SANDSTONE_STAIRS
  - SPRUCE_WOOD_STAIRS
  - JUNGLE_WOOD_STAIRS
  - QUARTZ_STAIRS
  - ACACIA_STAIRS
  - DARK_OAK_STAIRS
  - RED_SANDSTONE_STAIRS
  - BIRCH_WOOD_STAIRS
  - SPRUCE_WOOD_STAIRS
ignoreBlock:
  - STONE