mainServers:
  - Trinitos_Alpha
  - Trinitos_Beta
  - Trinitos_Gamma
  - Grun
  - Cetallion
  - Rakuria
  - Loyavas
  - Eratoss
  - Otavo
  - Sampetra
  - Uru
  - Tallimar
  - Nalavor
  - Avaquo
  - Xylos