name: ${project.name}
version: ${project.version}
main: nickmiste.SQTrade2

commands:
  buy:
    description: Used when buying from a dropper shop
    usage: /<command> <amount>

permissions:
  sqtrade.breakshops:
    description: Allows staff to break shops made by other players
