name: ${project.name}
main: com.ginger_walnut.sqdonation.SQDonation
version: ${project.version}
description: ${project.description}
commands:
   donation:
      description: Manages SQDonation
      aliases: [donations, donater, donaters, don]
permissions:
   SQDonation.viewHelp:
      description: Premission node for viewing help
      default: false
   SQDonation.setAmount:
      description: Premission node for changing the donation amount that somone has
      default: false