name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.ginger_walnut.sqdonation.SQDonation
depend: [StarQuest]

commands:
  donation:
    description: Manages SQDonation
    aliases: [donations, donater, donaters, don]
permissions:
  sqdonation.viewhelp:
    description: Premission node for viewing help
    default: false
  sqdonation.setamount:
    description: Premission node for changing the donation amount that somone has
    default: false