refugee:
    cost: 0
    kills: 0
settler:
    cost: 10000
    kills: 0
colonist:
    cost: 50000
    kills: 0
citizen:
    cost: 250000
    kills: 0
affluent:
    cost: 1250000
    kills: 0
tycoon:
    cost: 6250000
    kills: 0
pirate:
    cost: 0
    kills: 5
corsair:
    cost: 0
    kills: 20
buccaneer:
    cost: 0
    kills: 80
warlord:
    cost: 0
    kills: 160
multiplier: 1