name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Lyneira
website: http://dev.bukkit.org/server-mods/machinacraft/
dev-url: http://dev.bukkit.org/server-mods/machinacraft/
main: me.lyneira.HoverPad.HoverPadPlugin
depend: [MachinaCore]
permissions:
    hoverpad.all:
        description: Allows use of a hoverpad.
        children:
            hoverpad: true
    hoverpad:
        description: Allows use of a hoverpad.
        default: op