# Speed is measured in how long it takes for a block to break
# in ticks.
normal speed: 20
fast speed: 10
energy consumption per block: 50
max energy: 20000
testing version: false
# Fuel names are the same as the Bukkit API material names
fuel:
  COAL:
    energy per tick: 2
    burn time: 500
  WOOD:
    energy per tick: 4
    burn time: 100
  LOG:
    energy per tick: 4
    burn time: 400
  LOG_2:
    energy per tick: 4
    burn time: 400