name: ${project.name}
main: com.ginger_walnut.sqduties.SQDuties
version: ${project.version}
description: ${project.description}
commands:
   duty:
      description: toggles duty mode
   invrestore:
      description: restores inventory