name: ${project.name}
version: ${project.version}
description: ${project.description}
author: dibujaron
website: http://starquestminecraft.com
main: com.starquestminecraft.sqcontracts.SQContracts
depend: [StarQuest, Movecraft]

commands:
  contract:
    description: contract master command.
    usage: Do /contract help to view a list of commands
