name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.ginger_walnut.sqexpboost.Main

commands:
  expboost:
    description: Manages SQExpBoost
  expboost help:
    description: Shows the help for SQExpBoost
  expboost set:
    description: Sets the base exp multiplier

permissions:
  sqexpboost.viewhelp:
    description: Premission node for viewing help
    default: false
  sqexpboost.setmultiplier:
    description: Premission node for setting multiplier
    default: false
  sqexpboost.addmultiplier:
    description: Premission node for adding to the multiplier
    default: false
  sqexpboost.subtractmultiplier:
    description: Premission node for subtracting to the multiplier
    default: false