name: ${project.name}
version: ${project.version}
main: com.burkentertainment.SQPlanet.SQPlanetPlugin

commands:
  sqplanet:
    description: Control and edit spawning planet customization rules
    permission: sqplanet.admin
    permission-message: Missing permissions to edit SQPlanet settings
    usage: /SQPlanet reload

permissions:
  sqplanet.admin:
    description: Allows administrative access to SQPlanet
   